// Filesystem confinement.
//
// This is a security boundary and it had no tests. Its own header records the
// incident that created it — an agent told to write `outputs/SHIPPED.txt`
// created it two directories up and invented a phantom workspace on the way —
// so the cases below are the ones that must keep failing.
//
//   node --test tests/confine.test.ts

import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { checkPaths, checkBash } from "../packages/core/src/confine.ts";

const WORKSPACE = "/data/acme/workspaces/desk";
const ROOTS = {
  agentDir: `${WORKSPACE}/agents/writer`,
  workspaceRoot: WORKSPACE,
  libraryRoot: "/data/acme/library",
};

const write = (p: string) => checkPaths("Write", { file_path: p }, ROOTS);

test("an agent may write inside its own workspace", () => {
  for (const p of [
    `${ROOTS.agentDir}/outputs/draft.md`,
    `${ROOTS.agentDir}/memory/what-i-learned.md`,
    `${WORKSPACE}/agents/checker/outputs/report.md`, // a teammate's output: same workspace
  ]) {
    assert.equal(write(p).ok, true, `${p} should be allowed`);
  }
});

test("escaping the workspace is denied", () => {
  for (const p of [
    "/etc/passwd",
    `${WORKSPACE}/../other-workspace/agents/x/agent.md`,
    `${WORKSPACE}/../../secrets.json`,
    `${ROOTS.agentDir}/../../../../SHIPPED.txt`, // the original incident
  ]) {
    const v = write(p);
    assert.equal(v.ok, false, `${p} must be denied`);
    assert.match(v.reason ?? "", /outside this workspace|protected platform file/);
  }
});

test("secrets are never a file an agent can read", () => {
  for (const p of [`${WORKSPACE}/secrets.json`, "/data/acme/library/secrets.json"]) {
    assert.equal(checkPaths("Read", { file_path: p }, ROOTS).ok, false, p);
  }
});

test("the run journal is read-only", () => {
  for (const p of [`${WORKSPACE}/runs/run-123.json`, `${WORKSPACE}/runs`]) {
    assert.equal(write(p).ok, false, p);
  }
});

test("a memory bundle's generated index and log are protected", () => {
  // Regenerated by syncBundleFor on every write, so an agent editing one is
  // writing something about to be overwritten — and until it is, the index
  // says whatever it was told to. memory/ is the case that matters: it is the
  // one bundle an agent may write to at all.
  for (const p of [
    `${WORKSPACE}/memory/index.md`,
    `${WORKSPACE}/memory/log.md`,
    `${ROOTS.agentDir}/memory/index.md`, // the agent's own bundle
    `${ROOTS.agentDir}/memory/archive/index.md`, // nested section
  ]) {
    const v = write(p);
    assert.equal(v.ok, false, `${p} must be denied`);
    assert.match(v.reason ?? "", /generated from the files around them/);
  }
});

test("knowledge/ is read-only to an agent, index or not", () => {
  // A separate and older rule: knowledge is given, memory is learned. Asserted
  // here because it is the reason the rule above only has to name memory.
  for (const p of [
    `${WORKSPACE}/knowledge/pricing.md`,
    `${WORKSPACE}/knowledge/index.md`,
    `${WORKSPACE}/knowledge/gauges/index.md`,
  ]) {
    const v = write(p);
    assert.equal(v.ok, false, `${p} must be denied`);
    assert.match(v.reason ?? "", /maintained by people|generated from the files/);
  }
  // Reading it is the whole point of it existing.
  assert.equal(checkPaths("Read", { file_path: `${WORKSPACE}/knowledge/pricing.md` }, ROOTS).ok, true);
});

test("an ordinary index.md is not collateral damage", () => {
  // The rule names knowledge/ and memory/ precisely so a deliverable called
  // index.md is still an ordinary file.
  for (const p of [
    `${ROOTS.agentDir}/outputs/index.md`,
    `${WORKSPACE}/outputs/site/index.md`,
    `${ROOTS.agentDir}/skills/writing/references/index.md`,
  ]) {
    assert.equal(write(p).ok, true, `${p} should be allowed`);
  }
});

test("a memory concept file is still writable", () => {
  // Memory is agent-writable by design; only the derived files are not.
  assert.equal(write(`${ROOTS.agentDir}/memory/house-tone.md`).ok, true);
});

test("bash that reaches outside the workspace is denied", () => {
  for (const cmd of [
    "cat /etc/passwd",
    "cd /",
    "cd ~",
    // `~` used to be guarded only for `cd`, so these two walked past the
    // second layer entirely — the obvious escapes it exists to name.
    "cat ~/.ssh/id_rsa",
    "cp ~/.aws/credentials .",
    "cat ../../../../../etc/hosts",
    "echo $ANTHROPIC_API_KEY",
  ]) {
    assert.equal(checkBash(cmd).ok, false, `${cmd} must be denied`);
  }
});

test("ordinary bash is allowed", () => {
  // `cd ../..` is the workspace root from an agent directory — ordinary work.
  for (const cmd of [
    "python3 scripts/pace.py --spent 10",
    "ls outputs/",
    "cd ../.. && ls",
    "echo done > outputs/x.txt",
  ]) {
    assert.equal(checkBash(cmd).ok, true, cmd);
  }
});

// The protections checkPaths applies to Write and Edit have to hold for Bash
// too, or `bash` in an agent's tools: is a way around them. It was: Write to
// knowledge/ was denied while `echo x > knowledge/prices.md` went through, and
// the run journal — the thing every other guarantee is verified against — could
// be rewritten by any agent granted a shell.
test("bash cannot write where the file tools may not", () => {
  for (const cmd of [
    "echo free > ../../knowledge/pricing.md",
    "echo x >> knowledge/p.md",
    "rm ../../knowledge/pricing.md",
    "sed -i s/400/0/ knowledge/p.md",
    "echo x | tee knowledge/p.md",
    "mv /tmp/x knowledge/p.md",
    // The journal is denied outright, reads included: a rule that differs by
    // tool is a rule an agent can shop around for.
    "echo x > ../../runs/r.json",
    "cat ../../runs/r.json",
    "echo x > memory/index.md",
  ]) {
    assert.equal(checkBash(cmd).ok, false, `${cmd} must be denied`);
  }
});

// The counterpart, and the reason knowledge/ is matched only alongside a
// writing shape: reading the price list is the whole point of having one, so a
// blanket rule would have banned `cat` to close a hole about `>`.
test("bash may still read knowledge and write everywhere it should", () => {
  for (const cmd of [
    "cat ../../knowledge/pricing.md",
    "grep -r surcharge knowledge/",
    "cat knowledge/p.md && echo done",
    "echo learned > memory/note.md",
    "echo draft > outputs/draft.md",
    "mkdir -p outputs/sub",
  ]) {
    assert.equal(checkBash(cmd).ok, true, cmd);
  }
});
